use std::collections::HashMap;

const INPUT: &'static [&str] = &[
    "rvefnvyxzbodgpnpkumawhijsc",
    "rvefqtyxzsddglnppumawhijsc",
    "rvefqtywzbodglnkkubawhijsc",
    "rvefqpyxzbozglnpkumawhiqsc",
    "rvefqtyxzbotgenpkuyawhijsc",
    "rvefqtyxzbodglnlkumtphijsc",
    "rwefqtykzbodglnpkumawhijss",
    "rvynqtyxzbodglnpkumawrijsc",
    "rvefqtyxlbodgcnpkumawhijec",
    "rvefqtyxzbodmlnpnumawhijsx",
    "rvefqtyxzbqdbdnpkumawhijsc",
    "rvefqtyxzlodblnpkuiawhijsc",
    "rvefqtyizrodelnpkumawhijsc",
    "rveffjyxzgodglnpkumawhijsc",
    "rvefqjyxzbodalnpkumadhijsc",
    "rvefqtidzbodglnpkumawhdjsc",
    "hvefqtygzbodglnpkumawhijfc",
    "rzefqtyxzbodglfhkumawhijsc",
    "rmefqtyxzbolglnpkumaehijsc",
    "rnefqqyxzbodglnhkumawhijsc",
    "rvwfqvyxzbodglnpcumawhijsc",
    "rvefqtyxzbokgltpkumavhijsc",
    "rvefciyxzbodglnmkumawhijsc",
    "rvefptyxzbodglnpkuhashijsc",
    "rvefqtyxzrodglnpkxmawhiqsc",
    "rvefqtyxzbotglnpkumawriwsc",
    "rvufqtyxzbodglnplumawhijvc",
    "rvefutykzbodglnpkumaahijsc",
    "rvefqtyxqbodgllprumawhijsc",
    "rvegqttxzbodgllpkumawhijsc",
    "dvefqtyxzsodglnpkumawdijsc",
    "rvefqtyxkbodglnfkumawhijsj",
    "rvefqtyxzbodnlnpcumawhijnc",
    "rvefqtyxzbodglfpkuocwhijsc",
    "rvecqtyxzbbdganpkumawhijsc",
    "rvefytyxzbodglnpkubgwhijsc",
    "rvefxtyazbomglnpkumawhijsc",
    "rvefqgyxzbodglnpkumawyiksc",
    "avefqtyxzbodglnfkummwhijsc",
    "fvefqtyxzbbdglnpkumswhijsc",
    "rvefqtyxzxodglnpkumuuhijsc",
    "rvezqtyxzbydclnpkumawhijsc",
    "rvefqtyxzbohglnpkumawdijjc",
    "rvejqtyxzbodrlnpkumawhijsd",
    "rvefitzxzbxdglnpkumawhijsc",
    "rvefutyxzbvdglnikumawhijsc",
    "rvefqtyazbodgqnbkumawhijsc",
    "rvefqtyxzbolglnpkwmajhijsc",
    "rvefqtyxzjodglnpgwmawhijsc",
    "rvefhtyxzbodglbpaumawhijsc",
    "mvexqtyxzbodglnpkumawrijsc",
    "rvefqtyxwbodglnpkumawhbxsc",
    "rvefqtyxzbodgsnpkudawsijsc",
    "rvwfqtyxzbonglnwkumawhijsc",
    "rvefqtyxzjodglnpkfmawhwjsc",
    "rvefqtyxzbodglntkumughijsc",
    "rvefctyxzbodglnpkumawhiwsx",
    "avefqtyvzbodglnpkumawhijsb",
    "rfefqtyxzlodglnphumawhijsc",
    "rvefqtyxzfowglnpkumaehijsc",
    "rvhfvtyxzbodgqnpkumawhijsc",
    "rfefqtyxzbodglapkumuwhijsc",
    "rvefqclxzbodglnzkumawhijsc",
    "qvefqtyxzbodglnckumcwhijsc",
    "rvefqtyxzkodglnpkymawgijsc",
    "rvefqtyxzbodgfnpkumafhizsc",
    "rvefqtyxzbodglnxkumavhijsf",
    "rvevqtyxzbodgpnpkurawhijsc",
    "rvefqtyxziodglnpkubawhijss",
    "rrefqtpxzyodglnpkumawhijsc",
    "rvefqfyxzbodglcpkxmawhijsc",
    "rvefdtyxzbodglnpkumvwhijsn",
    "rverqtyxzbodglnpkwmawhijuc",
    "rvecjtyxzboxglnpkumawhijsc",
    "rvefqtyxzbodglnpkqmaxhifsc",
    "rtnfqtyxzbodglnpkumawhijmc",
    "lvefqtyxzbodelnpkumawhijsz",
    "dvefqtyxzbbdgvnpkumawhijsc",
    "rvefqlyhzbodglnpkumtwhijsc",
    "roefqtyxlbodglnpkumawhyjsc",
    "rvefqsydzjodglnpkumawhijsc",
    "rveybtyxzbodglnpkumawhijsn",
    "rvefqtyhzbodgvnpmumawhijsc",
    "rvefqxyazboddlnpkumawhijsc",
    "vvefqtyxzbohglqpkumawhijsc",
    "reefhtyxzbodglnpkkmawhijsc",
    "rvefqtyxzbodglnpkulowhijrc",
    "rveqqtyxzbodgknpkumawhijsk",
    "jvefqtqxzbodglnpkumawiijsc",
    "rvefqtyxzboxglnpvuqawhijsc",
    "rvefquyxzbodglwwkumawhijsc",
    "rvefqtyxzbodnlnpkumawhgjbc",
    "rvdfqthxdbodglnpkumawhijsc",
    "rvefqtyxzbodllnpkumawhujsb",
    "evefqtyxzboyglnpkumowhijsc",
    "rvefktyxzbomglnpzumawhijsc",
    "rvefqtyxzbodhlnnkrmawhijsc",
    "rvefqtyxrbodglnpkujaehijsc",
    "rvefqtyzzbodglnpkumrwhijsb",
    "evefqtyxzpodglfpkumawhijsc",
    "rvefqtyxibodglkpyumawhijsc",
    "rrefqtyxzbodglnpkudawhajsc",
    "rvifqtyxzbodglxpkumawhijlc",
    "rxefqtyxzbedglnpkumawhijsp",
    "rvnfqtyxzbopglnpkuqawhijsc",
    "rvefqtyxkbodglnpoumawoijsc",
    "dvefwtyxzbodglnpksmawhijsc",
    "rvkfqtyxzbodglnpkdmawhijsa",
    "rcefytyxzzodglnpkumawhijsc",
    "rvefqtkxzbodglnpktqawhijsc",
    "nvezqhyxzbodglnpkumawhijsc",
    "rrefqtyxzbodgunpkumpwhijsc",
    "rvefqtaxzbodgknpkumawhijic",
    "pvefqtyxzbodglnpkuxawsijsc",
    "rvefqtyxzbodglkpvumawhjjsc",
    "wvefqtyxzkodglnpkumawhhjsc",
    "rzefqtyxzbotglnpkumawhxjsc",
    "rvefqtxpzbodglnpkumawzijsc",
    "bgefqtyxzbodglnpkrmawhijsc",
    "rvefqlyxzbodglnpkumilhijsc",
    "cbefqtyxzbodglnpkumawhiesc",
    "rvefqtyxzbydelnpkumahhijsc",
    "rvefntyxzbodglnpkumaehijsw",
    "rverqtyxztodglopkumawhijsc",
    "rvefqtyxzdodgwrpkumawhijsc",
    "rvefqtyxibodglnikumawhtjsc",
    "qvafqtyxzbodglnpkurawhijsc",
    "rvefqtyxwbodglnpaumawoijsc",
    "rvefqtyxzoodglndknmawhijsc",
    "rvdfqtlxzyodglnpkumawhijsc",
    "rvefqtyxzbodglngfumawhinsc",
    "rsefqtyxzbodglnpkumawhijek",
    "rvoestyxzbodglnpkumawhijsc",
    "svefqtyxzboaglnprumawhijsc",
    "rvefqtybzbodgwnpkumawwijsc",
    "rvefqtyxzdwdglnpkvmawhijsc",
    "rvlfqtyxzbodglnpkrmawhixsc",
    "rvefqtyxwbodglepkumawhijsd",
    "rvefqtbxzbodglnqkumawhijmc",
    "rvefqtzxzbodglnpkumuzhijsc",
    "rvefqtyxzbodglnpkumawzwnsc",
    "rvwfqtyxzboiglnpkumawhijsg",
    "rtehotyxzbodglnpkudawhijsc",
    "rvegqtyxzbodglnpyumawhijsl",
    "rvecqtyxzbsdglnpkumawhojsc",
    "rvefqtyxzbodmlnpkumaghijfc",
    "rvefqtyxzxodglnpkumanvijsc",
    "rvefqtyxzbodglnbiugawhijsc",
    "lvefqtlxzbodglnplumawhijsc",
    "rvefqtyxvbodglnpkumaldijsc",
    "rmefqtyxzbodgvnpkuuawhijsc",
    "rvefqtyxzbodglnpkymeuhijsc",
    "rvefqtyxzuodganpsumawhijsc",
    "rxefqtyxzbodglnpkumgwhijwc",
    "rvefgtyxzbodglnpkudawxijsc",
    "ahefqtyxzbodglnpkumawhejsc",
    "rfefqtyxzbzdglnpkusawhijsc",
    "rvefqtyszqodgljpkumawhijsc",
    "rvefqtylzboiglnpkumrwhijsc",
    "rvefqtyxzltdglnpkumawhijsu",
    "rbefqtyxzbodglnpqumawhijsi",
    "rvefqtyozpodglnpkumawhijsa",
    "zvefqtyxzpopglnpkumawhijsc",
    "rvefqtyxzbodglnfkqmawhijsp",
    "rvefqtyxzbodgliakumawhijsf",
    "rvefqtymzrodgfnpkumawhijsc",
    "ivejqtyxzbodglnpkumawhijuc",
    "rvefqtyxzbodflnpkxwawhijsc",
    "dvrfqtyxzbodglnpkumashijsc",
    "rqefqtyxzbwdglnpkumawvijsc",
    "tvefqtkxzbodgltpkumawhijsc",
    "rvefdtyxzbodguxpkumawhijsc",
    "rveqqtyxvbodglnykumawhijsc",
    "rvefqtypzcovglnpkumawhijsc",
    "rvefqnyxzbosglnpkumdwhijsc",
    "rvefstjxzbodslnpkumawhijsc",
    "rvefqzyxzpodglnpkummwhijsc",
    "rvefqkyxzbodglnhgumawhijsc",
    "rvufqvyxzbodklnpkumawhijsc",
    "rvefotyxzhodglnpkumawhijsk",
    "rvefqtyxzbokglnpkumawvcjsc",
    "lvefqtyxzbolglnpkumawoijsc",
    "rvefqtywzoodglfpkumawhijsc",
    "rvehqtqxzbodglnpkumawhcjsc",
    "rqefqtyxzbodolnpkumjwhijsc",
    "rvefqtyxzbodglrpkunawgijsc",
    "rvefqtyxzbodglamkumawdijsc",
    "rvefvtyzzbodllnpkumawhijsc",
    "rvefqtyxzbldglnpfcmawhijsc",
    "rvefppyxzbodglnpkucawhijsc",
    "rvefquyuzbodglnpkumkwhijsc",
    "rvefqtyxzbodgqxpkumawhivsc",
    "rtefotyxzbodglnpkudawhijsc",
    "rvefqtyxzbodgbnmkuzawhijsc",
    "ivefqtyxzbodgsnpkumzwhijsc",
    "rvhfqtyxzbodolnpkumawhijsz",
    "rvefvtyxzbodwlnpkusawhijsc",
    "riemqtyxzbodglnpkumawhiasc",
    "rvtfqtyxzbqdglnpkumawuijsc",
    "raesqtyxzbodglnpkumawhijsj",
    "rvefqtyxzbodalmpkumawhihsc",
    "rvefqtlxzbodgznpkkmawhijsc",
    "rvefqbyxzbodglgpkubawhijsc",
    "rvefqtyxnbodgxnpkumswhijsc",
    "rvefqtyxzkodvlnukumawhijsc",
    "rvefqtyzzbocglnpkumafhijsc",
    "rvhfqtyxzbodglmpkumgwhijsc",
    "rvsfrtyxzbodnlnpkumawhijsc",
    "rvefqtyxzbxdglnpkujcwhijsc",
    "rvefqtyvzrodglnphumawhijsc",
    "reetatyxzbodglnpkumawhijsc",
    "rvefqtyxzbodglnpzumaoqijsc",
    "ovefqtyyzbodglnvkumawhijsc",
    "rvefqbyxzbodnlnpkumawhijsi",
    "xvefqtyxzbodgrnpkumawrijsc",
    "rvebqtyxzbodglnpkumazhiasc",
    "rqeretyxzbodglnpkumawhijsc",
    "rvefqtyxzyodglapkumvwhijsc",
    "rvesqxyxzbodglnpvumawhijsc",
    "rvefqtyxeborglnpkufawhijsc",
    "rvecqtyxzbodflnpkumawnijsc",
    "rvefdpyxtbodglnpkumawhijsc",
    "rvefqtyfzbodclnpkymawhijsc",
    "rvefqtywzbodglnpxumawhiusc",
    "rvefqtyxzbodglnpkumawzbjwc",
    "rvewqtyxdbodglnpxumawhijsc",
    "rvefqtyxzgocglnpkgmawhijsc",
    "rvufqtyxzbodggnpkuzawhijsc",
    "rvefqtynzlodgllpkumawhijsc",
    "rvedqtyxzbodghnpkumawhujsc",
    "rvefqtyxlbodgnnpkpmawhijsc",
    "rvefqtyxzboqglnpkzmawhijec",
    "rvefqtyxzbodglnpkfmwwyijsc",
    "rwefqtkxzbodzlnpkumawhijsc",
    "rvefqtyxvbodglnpkufawhyjsc",
    "rvefqtyxzbodgltpkumawhqmsc",
    "rvefctyxzbodglfpkumathijsc",
    "rvefqtyxzbodgfnpkuuawhijfc",
    "rvefqttxzbodglnpmumawhijwc",
    "rvefqtyxzbodglnpkqmawhihsj",
    "rvefqtyxzbsdglcnkumawhijsc",
    "rvbiqtyxzbodglnpkumawhijlc",
    "rnefqtylzvodglnpkumawhijsc",
    "mvefqtyxzbddglnpkumcwhijsc",
    "rvefwtyxzbodglnpkgmawhijxc",
    "rvefqtyxljodglnpkumxwhijsc",
    "rvefqtyxzbodglnpkuprwhijsd",
    "rcxfqtyxzbldglnpkumawhijsc",
    "rvetqtyxzbojglnpkumewhijsc",
    "rvxfqtyxzbtdglnpkbmawhijsc",
];

fn main() {
    let mut exactly_two = 0;
    let mut exactly_three = 0;

    for (_, item) in INPUT.iter().enumerate() {
        let mut frequencies = HashMap::new();

        for (_, c) in item.chars().enumerate() {
            let frequency = frequencies.entry(c).or_insert(0);
            *frequency += 1;
        }

        let mut has_exactly_two = false;
        let mut has_exactly_three = false;

        for (_, &frequency) in frequencies.iter() {
            if frequency == 2 {
                has_exactly_two = true;
            }
            if frequency == 3 {
                has_exactly_three = true;
            }
        }

        if has_exactly_two {
            exactly_two += 1;
        }

        if has_exactly_three {
            exactly_three += 1;
        }
    }

    println!(
        "exactly_two={}, exactly_three={}",
        exactly_two, exactly_three,
    );
}
